### ISSUE TITLE
User use description

### ISSUE THREAD

**Issue by choquette33** [PeaceCorps/realtrack-android#45]
Here's the full review: 

Great way to track projects for ease of filling out VRF This app makes it so much easier to keep track of my projects! I also don't like that I had to enter a reminder before I could add attendance and supplemental info. It also would be nice if there was a way to attach a couple photos. But, overall, very pleased. It helped me tremendously as I filled out my Volunteer Report Form since I could use more accurate information (and didn't have to sift through various attendance sheets!). Here's how I use it: My primary activity is listed as "Work with Counterparts". Then I created repeating activities for each counterpart to keep track of our work. My secondary activities are "English Classes", "Youth Groups", and "Other". I create different repeating activities for each English class and individual tutoring that I offer, the different youth groups and youth camps I am planning, and each "other" activity I do (helping other volunteers, student contests, technical seminars, meetings with the Ministry of Education, health seminars, etc.). I am able to easily keep track of attendance and impact! Great product! --Current Peace Corps Panama Volunteer

**Comment by neerajrao** [comment]
Nice to see feedback, thanks!
